//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Calender.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Userprofile
    {
        public int iduserprofile { get; set; }
        public Nullable<int> userid { get; set; }
        public string address1 { get; set; }
        public string address2 { get; set; }
        public string city { get; set; }
        public string state { get; set; }
        public string country { get; set; }
        public string zipcode { get; set; }
        public string cellphone { get; set; }
        public string homephone { get; set; }
        public string workphone { get; set; }
    
        public virtual User user { get; set; }
    }
}
