//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Calender.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Userlogin
    {
        public int iduserlogin { get; set; }
        public int userid { get; set; }
        public string encryptkey { get; set; }
        public string encryptvalue { get; set; }
        public Nullable<System.DateTime> create_time { get; set; }
        public string cookie { get; set; }
        public string form { get; set; }
    
        public virtual User User { get; set; }
    }
}
